### ISSUE TITLE
Best approach for cart page population

### ISSUE THREAD

**Issue by ConnorTurnbull** [ConnorTurnbull/Project-5-Build-an-E-Commerce-Website-with-Javascript#3]
- Current thought on this would be to take product ID plus user inputs (quantity & color) and store in local storage for cart page to recall, then populate the rest of the cart page elements from the API (images, names etc) once the item ID is known.

- Alternative method I thought of would be to store every element the cart pages requires in local storage and recalling from there. Assume this isn't really the way due to impact on page performance due to file sizes etc?

- Elements required for cart page:
![image](https://user-images.githubusercontent.com/110614970/219206476-9aa99f65-eeec-4f97-be8f-c7d85152e140.png)

**Comment by AccessiT3ch** [comment]
@ConnorTurnbull Ah that's a great question, I tend to suggest just saving the full product information to the cart (with an additional `quantity` property) so that you have all the data you need by the time you hit the cart page. Alternatively, as you described, you could save the bare minimum to localStorage and then query the API for the product info when the page loads. Both approaches are acceptable since you're either saving more data to localStorage or you're making more API requests, so I think it's a bit of a wash in terms of performance.

Note: localStorage has up to 5Mb of space, and since the data schema is pretty simple and since we can expect the users' carts to be fairly reasonable, there shouldn't be too much of a performance hit in this scenario. If that data got too big though, you're right it would be a matter of performance, but that would honestly have to have at least hundreds of array items each with at least dozens of properties. Even then I don't think it would come close to the 5Mb cap. Totally feasible in other contexts, but here I think it won't make a difference :)

**Comment by ConnorTurnbull** [comment]
@AccessiT3ch Great! Thanks for clearing that up for me.
