### ISSUE TITLE
Quantity functionality

### ISSUE THREAD

**Issue by ConnorTurnbull** [ConnorTurnbull/Project-5-Build-an-E-Commerce-Website-with-Javascript#4]
- Partial edit quantity functionality added for cart page.
- I feel like it's pretty close, though probably a little too basic / too many steps:

![image](https://user-images.githubusercontent.com/110614970/223135816-eb9f266a-3e6b-43b2-a533-1a0678d30f7a.png)

- Updates the 'selectedQuantity' in local storage for the correct item with the new input value but errors out on refresh:

![image](https://user-images.githubusercontent.com/110614970/223134778-f84c0fdc-104b-4ba8-a145-d633be29c5e2.png)

- Guessing an issue with the way the new value and cart is parsed to storage?

**Comment by AccessiT3ch** [comment]
@ConnorTurnbull This looks pretty good up until the body of the if statement towards the end, where is `selectedQuantity` being first defined? Without `const` or `let` it's either being defined outside this function or it's being defined on `window`. Then the right side of that same line looks a little unexpected, typically we don't have more than one `=` on a single line, it looks like the second `=` is being resolved in the `(..)`, it's not returning anything so that line isn't really defining anything (other than mutating the `selectedQuantity` on the `existingItem`.  You can probably simplify that line by just having the contents of the parenthesis, you also don't need to `0 + newQuantity` as it should already be a number.

Secondly, when setting the item to local storage, it looks like you're overriding your `cart` with a single property `selectedQuantity`. Since `cartParse` is an array, it doesn't have the `selectedQuantity` property, which is why `JSON.stringify()` is erroring out (bc it's trying to stringify `undefined`).

Maybe the if statement might look something like this:

```js
if (existingItem) {
  existingItem.selectedQuantity = newQuant; // this will update the item in cartParse via mutation
  localStorage.setItem('cart', JSON.stringify(parseCart)); // set the updated parseCart to localStorage

  // either call a function to update the DOM based on the newly updated state
  // updateCartElements()

 // or do the DOM updates right here
 // target.getElementsByClassName(<qauntityTextSeclector>)[0].innerHTML = newQuant;
 // target.getElementsByClassName(<subTotalTextSelector>)[0].innerHTML = newQuant * existingItem.price;
 // document.getElementsByClassName(<totalTextSelector>)[0].innerHTML = <math>;
}
```

Doing this should effectively be updating the state, which you can then use to update the rest of the DOM accordingly. You could probably also then just add a bit of functionality to the same if statement to update the display text for the item quantity, line subtotal, and the cart total.

**Comment by ConnorTurnbull** [comment]
@AccessiT3ch Firstly, thanks for taking the extra time during the last session to run through some code with me. It's really helpful having that instant dialogue when I'm having issues or trying to pick new things up.

I've taken another look at the cart totals functionality as, if you recall, they weren't summing correctly when adding/removing items via the cart page itself. What was happening was the cart totals were being updated just using the values from the individual item that was being updated and not taking into account the rest of the cart.

![image](https://user-images.githubusercontent.com/110614970/224398632-e07d43b1-e810-4853-8223-6d74edef2633.png)

The simplest solution that I could come up with was to take the code for the initial cart total into it's own function and then call that in the two places that it's required on the cart page:

![image](https://user-images.githubusercontent.com/110614970/224401629-0cd2cf50-b3ee-431d-9131-82a3b5190190.png)

![image](https://user-images.githubusercontent.com/110614970/224402042-9c93714a-5c89-4e60-bd13-1c2bbb860442.png)

Functionally it appears to work fine, can you see or think of any potential issues with doing it this way?
I've also opted against creating and importing a separate file for the sake of a singular function and have instead defined the function at the start of the cart page js file. Again, any issues with this?

Repo is updated if you need to take a better look than screenshots.

**Comment by AccessiT3ch** [comment]
@ConnorTurnbull Absolutely, definitely wanted to make sure you were in a good place before hopping off! 

This functionality looks like a great implementation to me, it's simple and clear and I think it would be very easy to test! I can imagine in different contexts (like if you're using a frontend js framework) then you might delineate the responsibility of the function between updating the DOM and the maths involved.

In that case you would simply return the totals out of the function, use those returned values to update the state, and let the framework handle updating the DOM based on the changes to state.

In this case, since you have to manually update the DOM at some point AND the totals aren't really being saved to state, I think how you've structured this is spot on, great work!

**Comment by ConnorTurnbull** [comment]
@AccessiT3ch Great! Thanks for taking a look.
