### ISSUE TITLE
Delete item in cart only works once

### ISSUE THREAD

**Issue by ConnorTurnbull** [ConnorTurnbull/Project-5-Build-an-E-Commerce-Website-with-Javascript#5]
Hey @AccessiT3ch,

Just going over proj5 before I arrange the assessment and noticed that the total price and total quantity in the cart ([cart.js](https://github.com/ConnorTurnbull/Project-5/blob/3c07ac7ea99675aa7a4527630d2771cc93aab1e0/front/js/cart.js)) were not updating when items were being deleted.

I've tried just passing the updateTotals() function in again but that made no difference. However, using the contents of the function works to a point. It will delete an item as required and update both totals but only works the first time. Any items deleted after that aren't removed and reappear on refresh and the cart/totals don't update. Sure i'm probably missing something super simple but it's escaping me at the moment.

Cheers!

**Comment by AccessiT3ch** [comment]
@ConnorTurnbull - It looks like you need to call `updateTotals()` in your delete button event listener function, and I might suggest changing the updateTotals function to update the totals based on what's in localStorage rather than the constant `cartParse` so that there is a singular source of cart truth!
